import type {
  Brand,
  Category,
  Product,
  Review,
} from '@/entities/product/model/types';

/**
 * Bundled catalogue.
 *
 * This is the store's data in its simplest durable form. `repository.ts` is the
 * only module that reads it, so moving to Postgres means reimplementing that
 * one file against Prisma — nothing else in the app knows where products live.
 */

export const categories: Category[] = [
  {
    slug: 'gpu',
    name: 'Видеокарты',
    nameShort: 'видеокарт',
    description:
      'От тихих карт для монтажа до топовых RTX для 4K. Каждая карта проходит стресс-тест на стенде перед выдачей.',
    buildSlot: 'gpu',
  },
  {
    slug: 'cpu',
    name: 'Процессоры',
    nameShort: 'процессоров',
    description: 'AMD AM5 и Intel LGA1851 — с подбором материнской платы и охлаждения под сокет.',
    buildSlot: 'cpu',
  },
  {
    slug: 'motherboard',
    name: 'Материнские платы',
    nameShort: 'материнских плат',
    description: 'B650, X870E, B860 — от компактных ITX до плат под разгон памяти.',
    buildSlot: 'motherboard',
  },
  {
    slug: 'ram',
    name: 'Оперативная память',
    nameShort: 'комплектов памяти',
    description: 'DDR5 до 8000 МТ/с и DDR4 для апгрейда старых платформ. Комплекты проверены на XMP/EXPO.',
    buildSlot: 'ram',
  },
  {
    slug: 'storage',
    name: 'Накопители',
    nameShort: 'накопителей',
    description: 'NVMe Gen5 для рабочих станций, Gen4 для игр, HDD для архива.',
    buildSlot: 'storage',
  },
  {
    slug: 'psu',
    name: 'Блоки питания',
    nameShort: 'блоков питания',
    description: 'ATX 3.1 с нативным 12V-2x6 — то, что реально держит пиковые нагрузки новых видеокарт.',
    buildSlot: 'psu',
  },
  {
    slug: 'case',
    name: 'Корпуса',
    nameShort: 'корпусов',
    description: 'Продуваемые mesh-корпуса и тихие панели с шумоизоляцией.',
    buildSlot: 'case',
  },
  {
    slug: 'cooling',
    name: 'Охлаждение',
    nameShort: 'систем охлаждения',
    description: 'Башни и СЖО. Подбираем по TDP процессора и высоте корпуса, а не по картинке.',
    buildSlot: 'cooling',
  },
  {
    slug: 'monitor',
    name: 'Мониторы',
    nameShort: 'мониторов',
    description: 'OLED 240 Гц для соревновательных игр и IPS с заводской калибровкой для цвета.',
  },
  {
    slug: 'peripherals',
    name: 'Периферия',
    nameShort: 'устройств',
    description: 'Клавиатуры, мыши, гарнитуры и коврики — то, чего касаются руки каждый день.',
  },
  {
    slug: 'laptop',
    name: 'Ноутбуки',
    nameShort: 'ноутбуков',
    description: 'Игровые, рабочие и ультрабуки. С настройкой и переносом данных при покупке.',
  },
  {
    slug: 'prebuilt',
    name: 'Готовые сборки',
    nameShort: 'сборок',
    description: 'Собраны и протестированы в Махачкале. Кабель-менеджмент, прошивки, стресс-тест 4 часа.',
  },
];

export const brands: Brand[] = [
  { slug: 'nvidia', name: 'NVIDIA', country: 'США', categories: ['gpu'] },
  { slug: 'amd', name: 'AMD', country: 'США', categories: ['cpu', 'gpu'] },
  { slug: 'intel', name: 'Intel', country: 'США', categories: ['cpu'] },
  { slug: 'asus', name: 'ASUS', country: 'Тайвань', categories: ['motherboard', 'gpu', 'monitor', 'laptop'] },
  { slug: 'msi', name: 'MSI', country: 'Тайвань', categories: ['motherboard', 'gpu', 'monitor', 'laptop'] },
  { slug: 'gigabyte', name: 'Gigabyte', country: 'Тайвань', categories: ['motherboard', 'gpu'] },
  { slug: 'palit', name: 'Palit', country: 'Тайвань', categories: ['gpu'] },
  { slug: 'kingston', name: 'Kingston', country: 'США', categories: ['ram', 'storage'] },
  { slug: 'gskill', name: 'G.Skill', country: 'Тайвань', categories: ['ram'] },
  { slug: 'samsung', name: 'Samsung', country: 'Южная Корея', categories: ['storage', 'monitor'] },
  { slug: 'wd', name: 'Western Digital', country: 'США', categories: ['storage'] },
  { slug: 'seagate', name: 'Seagate', country: 'США', categories: ['storage'] },
  { slug: 'be-quiet', name: 'be quiet!', country: 'Германия', categories: ['psu', 'cooling', 'case'] },
  { slug: 'deepcool', name: 'DeepCool', country: 'Китай', categories: ['cooling', 'case', 'psu'] },
  { slug: 'thermalright', name: 'Thermalright', country: 'Китай', categories: ['cooling'] },
  { slug: 'lian-li', name: 'Lian Li', country: 'Тайвань', categories: ['case', 'cooling'] },
  { slug: 'corsair', name: 'Corsair', country: 'США', categories: ['psu', 'ram', 'peripherals'] },
  { slug: 'logitech', name: 'Logitech', country: 'Швейцария', categories: ['peripherals'] },
  { slug: 'razer', name: 'Razer', country: 'США', categories: ['peripherals'] },
  { slug: 'hyperx', name: 'HyperX', country: 'США', categories: ['peripherals'] },
  { slug: 'lg', name: 'LG', country: 'Южная Корея', categories: ['monitor'] },
  { slug: 'lenovo', name: 'Lenovo', country: 'Китай', categories: ['laptop'] },
  { slug: 'apple', name: 'Apple', country: 'США', categories: ['laptop'] },
  { slug: 'tochkacomp', name: 'TochkaComp', country: 'Россия', categories: ['prebuilt'] },
];

/* -------------------------------------------------------------------------- */

const p = (product: Product): Product => product;

export const products: Product[] = [
  /* ---------------------------------------------------------------- GPU -- */
  p({
    id: 'gpu-1',
    slug: 'palit-rtx-5070-ti-gamingpro-16gb',
    name: 'Видеокарта Palit GeForce RTX 5070 Ti GamingPro 16 ГБ',
    shortName: 'RTX 5070 Ti GamingPro',
    sku: 'NE7507T019T2-GB2031A',
    brand: 'palit',
    category: 'gpu',
    price: 94990,
    oldPrice: 108990,
    rating: 4.8,
    reviewCount: 64,
    availability: 'in_stock',
    stock: 7,
    badges: ['hit', 'sale'],
    highlights: [
      '4K/60 в большинстве проектов без апскейла',
      '16 ГБ GDDR7 — запас под текстуры и локальные модели',
      'Тихая под нагрузкой: 34 дБ в закрытом корпусе',
    ],
    description:
      'Универсальная карта верхнего среднего сегмента. Держит 4K с DLSS 4 и Frame Generation, при этом остаётся в пределах 300 Вт — не требует замены блока питания в большинстве апгрейдов.',
    specs: [
      { key: 'Графический процессор', value: 'GB203', primary: true },
      { key: 'Видеопамять', value: '16 ГБ GDDR7', primary: true },
      { key: 'Шина памяти', value: '256 бит' },
      { key: 'Частота Boost', value: '2452 МГц' },
      { key: 'Интерфейс', value: 'PCIe 5.0 x16' },
      { key: 'Разъёмы питания', value: '1 × 12V-2x6', primary: true },
      { key: 'Длина', value: '329 мм' },
      { key: 'Занимаемых слотов', value: '3' },
      { key: 'Рекомендуемый БП', value: '750 Вт' },
    ],
    warrantyMonths: 36,
    releasedAt: '2025-02-20',
    buildSlot: 'gpu',
    power: 300,
  }),
  p({
    id: 'gpu-2',
    slug: 'asus-tuf-rtx-5080-oc-16gb',
    name: 'Видеокарта ASUS TUF Gaming GeForce RTX 5080 OC 16 ГБ',
    shortName: 'RTX 5080 TUF OC',
    sku: 'TUF-RTX5080-O16G-GAMING',
    brand: 'asus',
    category: 'gpu',
    price: 168990,
    rating: 4.9,
    reviewCount: 31,
    availability: 'low_stock',
    stock: 2,
    badges: ['new'],
    highlights: [
      '4K/120 в киберспорте и 4K/60 с полной трассировкой',
      'Металлический кожух и подшипники с двойной защитой',
      'Двойной BIOS: тихий режим переключается тумблером',
    ],
    description:
      'Флагман для тех, кому нужен запас на четыре-пять лет. Система охлаждения TUF рассчитана на длительную нагрузку — рендер и обучение моделей, а не только вечерние сессии.',
    specs: [
      { key: 'Графический процессор', value: 'GB203', primary: true },
      { key: 'Видеопамять', value: '16 ГБ GDDR7', primary: true },
      { key: 'Шина памяти', value: '256 бит' },
      { key: 'Частота Boost', value: '2670 МГц' },
      { key: 'Интерфейс', value: 'PCIe 5.0 x16' },
      { key: 'Разъёмы питания', value: '1 × 12V-2x6', primary: true },
      { key: 'Длина', value: '340 мм' },
      { key: 'Занимаемых слотов', value: '3.5' },
      { key: 'Рекомендуемый БП', value: '850 Вт' },
    ],
    warrantyMonths: 36,
    releasedAt: '2025-01-30',
    buildSlot: 'gpu',
    power: 360,
  }),
  p({
    id: 'gpu-3',
    slug: 'gigabyte-rx-9070-xt-gaming-oc-16gb',
    name: 'Видеокарта Gigabyte Radeon RX 9070 XT Gaming OC 16 ГБ',
    shortName: 'RX 9070 XT Gaming OC',
    sku: 'GV-R9070XTGAMING-OC-16GD',
    brand: 'gigabyte',
    category: 'gpu',
    price: 78490,
    oldPrice: 84990,
    rating: 4.7,
    reviewCount: 48,
    availability: 'in_stock',
    stock: 11,
    badges: ['sale'],
    highlights: [
      'Лучший рубль за кадр в 1440p',
      '16 ГБ памяти при цене конкурентов с 12 ГБ',
      'FSR 4 и заметно подтянутая трассировка',
    ],
    description:
      'Разумный выбор для 2K с высоким герцовым монитором. Берёт большинство новых игр на ультра без апскейла и заметно дешевле ближайшего конкурента.',
    specs: [
      { key: 'Графический процессор', value: 'Navi 48', primary: true },
      { key: 'Видеопамять', value: '16 ГБ GDDR6', primary: true },
      { key: 'Шина памяти', value: '256 бит' },
      { key: 'Частота Boost', value: '2970 МГц' },
      { key: 'Интерфейс', value: 'PCIe 5.0 x16' },
      { key: 'Разъёмы питания', value: '2 × 8-pin', primary: true },
      { key: 'Длина', value: '331 мм' },
      { key: 'Занимаемых слотов', value: '3' },
      { key: 'Рекомендуемый БП', value: '750 Вт' },
    ],
    warrantyMonths: 36,
    releasedAt: '2025-03-06',
    buildSlot: 'gpu',
    power: 304,
  }),
  p({
    id: 'gpu-4',
    slug: 'msi-rtx-5060-ti-ventus-2x-16gb',
    name: 'Видеокарта MSI GeForce RTX 5060 Ti Ventus 2X OC 16 ГБ',
    shortName: 'RTX 5060 Ti Ventus 2X',
    sku: 'RTX 5060 Ti 16G VENTUS 2X OC',
    brand: 'msi',
    category: 'gpu',
    price: 48990,
    rating: 4.6,
    reviewCount: 92,
    availability: 'in_stock',
    stock: 18,
    badges: ['hit'],
    highlights: [
      'Точка входа в 1440p с комфортным запасом памяти',
      'Два слота — влезет в компактный корпус',
      'Питание 8-pin: подойдёт к старому БП на 600 Вт',
    ],
    description:
      'Самая частая карта в наших сборках до 150 000 ₽. 16 ГБ — то, из-за чего она стареет медленнее, чем версия на 8 ГБ.',
    specs: [
      { key: 'Графический процессор', value: 'GB206', primary: true },
      { key: 'Видеопамять', value: '16 ГБ GDDR7', primary: true },
      { key: 'Шина памяти', value: '128 бит' },
      { key: 'Частота Boost', value: '2617 МГц' },
      { key: 'Интерфейс', value: 'PCIe 5.0 x8' },
      { key: 'Разъёмы питания', value: '1 × 8-pin', primary: true },
      { key: 'Длина', value: '200 мм' },
      { key: 'Занимаемых слотов', value: '2' },
      { key: 'Рекомендуемый БП', value: '600 Вт' },
    ],
    warrantyMonths: 36,
    releasedAt: '2025-04-16',
    buildSlot: 'gpu',
    power: 180,
  }),

  /* ---------------------------------------------------------------- CPU -- */
  p({
    id: 'cpu-1',
    slug: 'amd-ryzen-7-9800x3d',
    name: 'Процессор AMD Ryzen 7 9800X3D',
    shortName: 'Ryzen 7 9800X3D',
    sku: '100-100001084WOF',
    brand: 'amd',
    category: 'cpu',
    price: 58990,
    rating: 4.9,
    reviewCount: 137,
    availability: 'in_stock',
    stock: 9,
    badges: ['hit'],
    highlights: [
      'Быстрейший игровой процессор на сегодня',
      '96 МБ 3D V-Cache снимает просадки в симуляторах и стратегиях',
      'Разблокированный множитель — в отличие от прошлого X3D',
    ],
    description:
      'Если сборка ради максимального FPS в 1080p и 1440p — выбор очевиден. Требует хорошей башни: 120 Вт под нагрузкой концентрируются на маленькой площади.',
    specs: [
      { key: 'Сокет', value: 'AM5', primary: true },
      { key: 'Ядра / потоки', value: '8 / 16', primary: true },
      { key: 'Базовая частота', value: '4.7 ГГц' },
      { key: 'Turbo', value: '5.2 ГГц' },
      { key: 'Кэш L3', value: '96 МБ', primary: true },
      { key: 'TDP', value: '120 Вт' },
      { key: 'Память', value: 'DDR5-5600' },
      { key: 'Техпроцесс', value: '4 нм' },
      { key: 'Кулер в комплекте', value: 'Нет' },
    ],
    warrantyMonths: 36,
    releasedAt: '2024-11-07',
    buildSlot: 'cpu',
    power: 120,
    socket: 'AM5',
    memoryType: 'DDR5',
  }),
  p({
    id: 'cpu-2',
    slug: 'amd-ryzen-5-9600x',
    name: 'Процессор AMD Ryzen 5 9600X',
    shortName: 'Ryzen 5 9600X',
    sku: '100-100001405WOF',
    brand: 'amd',
    category: 'cpu',
    price: 24490,
    oldPrice: 27990,
    rating: 4.7,
    reviewCount: 88,
    availability: 'in_stock',
    stock: 22,
    badges: ['sale'],
    highlights: [
      'Холодный: 65 Вт, хватает башни за 3 000 ₽',
      'Платформа AM5 живёт до 2027 года — апгрейд без смены платы',
      'Не станет узким местом ни для одной карты до RTX 5070 Ti',
    ],
    description:
      'Рабочая лошадь средней сборки. Шесть ядер Zen 5 закрывают игры и повседневные задачи, а низкий TDP упрощает и охлаждение, и корпус.',
    specs: [
      { key: 'Сокет', value: 'AM5', primary: true },
      { key: 'Ядра / потоки', value: '6 / 12', primary: true },
      { key: 'Базовая частота', value: '3.9 ГГц' },
      { key: 'Turbo', value: '5.4 ГГц' },
      { key: 'Кэш L3', value: '32 МБ' },
      { key: 'TDP', value: '65 Вт', primary: true },
      { key: 'Память', value: 'DDR5-5600' },
      { key: 'Техпроцесс', value: '4 нм' },
      { key: 'Кулер в комплекте', value: 'Нет' },
    ],
    warrantyMonths: 36,
    releasedAt: '2024-08-08',
    buildSlot: 'cpu',
    power: 65,
    socket: 'AM5',
    memoryType: 'DDR5',
  }),
  p({
    id: 'cpu-3',
    slug: 'intel-core-ultra-7-265k',
    name: 'Процессор Intel Core Ultra 7 265K',
    shortName: 'Core Ultra 7 265K',
    sku: 'BX80768265K',
    brand: 'intel',
    category: 'cpu',
    price: 43990,
    rating: 4.5,
    reviewCount: 41,
    availability: 'in_stock',
    stock: 6,
    badges: [],
    highlights: [
      '20 ядер — сильная многопоточка для монтажа и компиляции',
      'Встроенный NPU для локальных нейросетей',
      'Заметно холоднее прошлого поколения LGA1700',
    ],
    description:
      'Выбор, когда компьютер работает, а не только играет. В рендере и экспорте видео обходит восьмиядерники, в играх — примерно на уровне Ryzen 7.',
    specs: [
      { key: 'Сокет', value: 'LGA1851', primary: true },
      { key: 'Ядра / потоки', value: '20 / 20', primary: true },
      { key: 'P-ядра', value: '8 × до 5.5 ГГц' },
      { key: 'E-ядра', value: '12 × до 4.6 ГГц' },
      { key: 'Кэш L3', value: '30 МБ' },
      { key: 'TDP', value: '125 Вт', primary: true },
      { key: 'Память', value: 'DDR5-6400' },
      { key: 'Техпроцесс', value: '3 нм' },
      { key: 'Кулер в комплекте', value: 'Нет' },
    ],
    warrantyMonths: 36,
    releasedAt: '2024-10-24',
    buildSlot: 'cpu',
    power: 125,
    socket: 'LGA1851',
    memoryType: 'DDR5',
  }),

  /* -------------------------------------------------------- Motherboard -- */
  p({
    id: 'mb-1',
    slug: 'asus-tuf-gaming-b650-plus-wifi',
    name: 'Материнская плата ASUS TUF Gaming B650-PLUS WiFi',
    shortName: 'TUF B650-PLUS WiFi',
    sku: '90MB1BY0-M0EAY0',
    brand: 'asus',
    category: 'motherboard',
    price: 19990,
    rating: 4.7,
    reviewCount: 74,
    availability: 'in_stock',
    stock: 14,
    badges: ['hit'],
    highlights: [
      'Питание 12+2 фаз — тянет даже Ryzen 9 без троттлинга',
      'Wi-Fi 6E и 2.5G Ethernet на борту',
      'Три M.2, один из них с PCIe 5.0',
    ],
    description:
      'Плата, которую мы ставим в большинство сборок на AM5. Без лишних наценок за подсветку, но с полным набором того, что реально используется.',
    specs: [
      { key: 'Сокет', value: 'AM5', primary: true },
      { key: 'Чипсет', value: 'AMD B650', primary: true },
      { key: 'Форм-фактор', value: 'ATX', primary: true },
      { key: 'Слоты памяти', value: '4 × DDR5, до 192 ГБ' },
      { key: 'Разъёмы M.2', value: '3' },
      { key: 'Сеть', value: '2.5 Гбит/с + Wi-Fi 6E' },
      { key: 'USB на задней панели', value: '9' },
      { key: 'Питание CPU', value: '8+4 pin' },
    ],
    warrantyMonths: 36,
    releasedAt: '2023-09-12',
    buildSlot: 'motherboard',
    power: 45,
    socket: 'AM5',
    formFactor: 'ATX',
    memoryType: 'DDR5',
  }),
  p({
    id: 'mb-2',
    slug: 'msi-mag-x870-tomahawk-wifi',
    name: 'Материнская плата MSI MAG X870 Tomahawk WiFi',
    shortName: 'MAG X870 Tomahawk',
    sku: '911-7E51-001',
    brand: 'msi',
    category: 'motherboard',
    price: 34990,
    rating: 4.8,
    reviewCount: 29,
    availability: 'in_stock',
    stock: 5,
    badges: ['new'],
    highlights: [
      'USB4 40 Гбит/с — внешние SSD и мониторы по одному кабелю',
      'Разгон памяти до DDR5-8400',
      'Крепление M.2 и видеокарты без отвёртки',
    ],
    description:
      'Верхняя граница разумного на AM5. Берут под 9800X3D и быструю память, когда важно выжать платформу до конца.',
    specs: [
      { key: 'Сокет', value: 'AM5', primary: true },
      { key: 'Чипсет', value: 'AMD X870', primary: true },
      { key: 'Форм-фактор', value: 'ATX', primary: true },
      { key: 'Слоты памяти', value: '4 × DDR5, до 256 ГБ' },
      { key: 'Разъёмы M.2', value: '4' },
      { key: 'Сеть', value: '5 Гбит/с + Wi-Fi 7' },
      { key: 'USB на задней панели', value: '11, включая 2 × USB4' },
      { key: 'Питание CPU', value: '8+8 pin' },
    ],
    warrantyMonths: 36,
    releasedAt: '2024-09-30',
    buildSlot: 'motherboard',
    power: 55,
    socket: 'AM5',
    formFactor: 'ATX',
    memoryType: 'DDR5',
  }),
  p({
    id: 'mb-3',
    slug: 'gigabyte-b860m-gaming-wifi6e',
    name: 'Материнская плата Gigabyte B860M Gaming WiFi6E',
    shortName: 'B860M Gaming WiFi6E',
    sku: 'B860M GAMING WIFI6E',
    brand: 'gigabyte',
    category: 'motherboard',
    price: 17490,
    rating: 4.5,
    reviewCount: 22,
    availability: 'in_stock',
    stock: 8,
    badges: [],
    highlights: [
      'mATX — под компактный корпус',
      'Два M.2 с радиаторами из коробки',
      'Wi-Fi 6E без внешней антенны в комплекте',
    ],
    description: 'Компактная плата под LGA1851 для сборок, где важен размер, а не разгон.',
    specs: [
      { key: 'Сокет', value: 'LGA1851', primary: true },
      { key: 'Чипсет', value: 'Intel B860', primary: true },
      { key: 'Форм-фактор', value: 'micro-ATX', primary: true },
      { key: 'Слоты памяти', value: '4 × DDR5, до 192 ГБ' },
      { key: 'Разъёмы M.2', value: '2' },
      { key: 'Сеть', value: '2.5 Гбит/с + Wi-Fi 6E' },
      { key: 'USB на задней панели', value: '7' },
      { key: 'Питание CPU', value: '8+4 pin' },
    ],
    warrantyMonths: 36,
    releasedAt: '2025-01-10',
    buildSlot: 'motherboard',
    power: 40,
    socket: 'LGA1851',
    formFactor: 'micro-ATX',
    memoryType: 'DDR5',
  }),

  /* ---------------------------------------------------------------- RAM -- */
  p({
    id: 'ram-1',
    slug: 'gskill-trident-z5-neo-32gb-ddr5-6000',
    name: 'Оперативная память G.Skill Trident Z5 Neo RGB 32 ГБ DDR5-6000 CL30',
    shortName: 'Trident Z5 Neo 32 ГБ',
    sku: 'F5-6000J3038F16GX2-TZ5NR',
    brand: 'gskill',
    category: 'ram',
    price: 14990,
    oldPrice: 17490,
    rating: 4.9,
    reviewCount: 156,
    availability: 'in_stock',
    stock: 26,
    badges: ['hit', 'sale'],
    highlights: [
      'DDR5-6000 CL30 — золотая середина для Ryzen',
      'Профиль EXPO включается одной галочкой в BIOS',
      'Радиаторы 44 мм — не мешают большинству башен',
    ],
    description:
      'Комплект, который мы ставим по умолчанию в сборки на AM5. 6000 МТ/с с задержкой CL30 — режим, на котором контроллер памяти Ryzen работает синхронно и даёт максимум.',
    specs: [
      { key: 'Объём', value: '32 ГБ (2 × 16)', primary: true },
      { key: 'Тип', value: 'DDR5', primary: true },
      { key: 'Частота', value: '6000 МТ/с', primary: true },
      { key: 'Тайминги', value: 'CL30-38-38-96' },
      { key: 'Напряжение', value: '1.35 В' },
      { key: 'Профиль', value: 'AMD EXPO' },
      { key: 'Высота', value: '44 мм' },
      { key: 'Подсветка', value: 'RGB' },
    ],
    warrantyMonths: 120,
    releasedAt: '2024-05-14',
    buildSlot: 'ram',
    power: 12,
    memoryType: 'DDR5',
  }),
  p({
    id: 'ram-2',
    slug: 'kingston-fury-beast-64gb-ddr5-5600',
    name: 'Оперативная память Kingston FURY Beast 64 ГБ DDR5-5600 CL36',
    shortName: 'FURY Beast 64 ГБ',
    sku: 'KF556C36BBEK2-64',
    brand: 'kingston',
    category: 'ram',
    price: 26990,
    rating: 4.7,
    reviewCount: 43,
    availability: 'in_stock',
    stock: 10,
    badges: [],
    highlights: [
      '64 ГБ — для монтажа 4K и виртуалок',
      'Низкий профиль: совместим с любой башней',
      'Работает и на Intel (XMP), и на AMD (EXPO)',
    ],
    description:
      'Когда 32 ГБ уже мало: работа с многослойными проектами, локальные модели, несколько виртуальных машин одновременно.',
    specs: [
      { key: 'Объём', value: '64 ГБ (2 × 32)', primary: true },
      { key: 'Тип', value: 'DDR5', primary: true },
      { key: 'Частота', value: '5600 МТ/с', primary: true },
      { key: 'Тайминги', value: 'CL36-38-38' },
      { key: 'Напряжение', value: '1.25 В' },
      { key: 'Профиль', value: 'XMP 3.0 / EXPO' },
      { key: 'Высота', value: '34.9 мм' },
      { key: 'Подсветка', value: 'Нет' },
    ],
    warrantyMonths: 120,
    releasedAt: '2024-02-01',
    buildSlot: 'ram',
    power: 14,
    memoryType: 'DDR5',
  }),

  /* ------------------------------------------------------------ Storage -- */
  p({
    id: 'ssd-1',
    slug: 'samsung-990-pro-2tb',
    name: 'SSD Samsung 990 PRO 2 ТБ M.2 NVMe с радиатором',
    shortName: 'Samsung 990 PRO 2 ТБ',
    sku: 'MZ-V9P2T0CW',
    brand: 'samsung',
    category: 'storage',
    price: 21990,
    oldPrice: 24990,
    rating: 4.9,
    reviewCount: 211,
    availability: 'in_stock',
    stock: 31,
    badges: ['hit', 'sale'],
    highlights: [
      '7450 МБ/с чтение — карты в играх грузятся без подгрузок',
      'Радиатор в комплекте: не уходит в троттлинг под PS5/ПК',
      'Ресурс 1200 TBW и 5 лет гарантии',
    ],
    description:
      'Эталонный Gen4 накопитель. Быстрый в пике и, что важнее, стабильный на длинных записях — не проваливается после заполнения SLC-кэша.',
    specs: [
      { key: 'Объём', value: '2 ТБ', primary: true },
      { key: 'Интерфейс', value: 'PCIe 4.0 x4 NVMe', primary: true },
      { key: 'Форм-фактор', value: 'M.2 2280' },
      { key: 'Чтение', value: 'до 7450 МБ/с', primary: true },
      { key: 'Запись', value: 'до 6900 МБ/с' },
      { key: 'Ресурс', value: '1200 TBW' },
      { key: 'Радиатор', value: 'Да' },
      { key: 'Память', value: '3D V-NAND TLC' },
    ],
    warrantyMonths: 60,
    releasedAt: '2023-10-10',
    buildSlot: 'storage',
    power: 8,
  }),
  p({
    id: 'ssd-2',
    slug: 'wd-black-sn7100-1tb',
    name: 'SSD WD_BLACK SN7100 1 ТБ M.2 NVMe',
    shortName: 'WD_BLACK SN7100 1 ТБ',
    sku: 'WDS100T4X0E',
    brand: 'wd',
    category: 'storage',
    price: 9990,
    rating: 4.7,
    reviewCount: 118,
    availability: 'in_stock',
    stock: 40,
    badges: [],
    highlights: [
      'Без DRAM, но с очень низким энергопотреблением',
      'Холодный — можно ставить под видеокарту',
      'Оптимален как системный диск',
    ],
    description: 'Рациональный системный накопитель: скорость Gen4 без переплаты за пиковые цифры.',
    specs: [
      { key: 'Объём', value: '1 ТБ', primary: true },
      { key: 'Интерфейс', value: 'PCIe 4.0 x4 NVMe', primary: true },
      { key: 'Форм-фактор', value: 'M.2 2280' },
      { key: 'Чтение', value: 'до 7250 МБ/с', primary: true },
      { key: 'Запись', value: 'до 6900 МБ/с' },
      { key: 'Ресурс', value: '600 TBW' },
      { key: 'Радиатор', value: 'Нет' },
      { key: 'Память', value: 'BiCS8 TLC' },
    ],
    warrantyMonths: 60,
    releasedAt: '2025-02-11',
    buildSlot: 'storage',
    power: 6,
  }),
  p({
    id: 'hdd-1',
    slug: 'seagate-ironwolf-8tb',
    name: 'Жёсткий диск Seagate IronWolf 8 ТБ 3.5" NAS',
    shortName: 'IronWolf 8 ТБ',
    sku: 'ST8000VN004',
    brand: 'seagate',
    category: 'storage',
    price: 23490,
    rating: 4.6,
    reviewCount: 37,
    availability: 'in_stock',
    stock: 6,
    badges: [],
    highlights: [
      'Рассчитан на круглосуточную работу',
      'Датчики вибрации для многодисковых корзин',
      'Три года гарантии и восстановление данных',
    ],
    description: 'Архив, бэкапы, видеонаблюдение. Там, где нужен объём, а не скорость.',
    specs: [
      { key: 'Объём', value: '8 ТБ', primary: true },
      { key: 'Интерфейс', value: 'SATA 6 Гбит/с', primary: true },
      { key: 'Форм-фактор', value: '3.5"' },
      { key: 'Скорость вращения', value: '7200 об/мин', primary: true },
      { key: 'Кэш', value: '256 МБ' },
      { key: 'Нагрузка', value: '180 ТБ/год' },
      { key: 'Уровень шума', value: '28 дБ' },
    ],
    warrantyMonths: 36,
    releasedAt: '2022-06-01',
    buildSlot: 'storage',
    power: 10,
  }),

  /* ---------------------------------------------------------------- PSU -- */
  p({
    id: 'psu-1',
    slug: 'be-quiet-pure-power-13-m-850w',
    name: 'Блок питания be quiet! Pure Power 13 M 850 Вт 80+ Gold ATX 3.1',
    shortName: 'Pure Power 13 M 850W',
    sku: 'BN376',
    brand: 'be-quiet',
    category: 'psu',
    price: 15490,
    rating: 4.8,
    reviewCount: 66,
    availability: 'in_stock',
    stock: 13,
    badges: ['hit'],
    highlights: [
      'ATX 3.1 с нативным 12V-2x6 — без переходников',
      'Держит пики видеокарты до 200 % номинала',
      'Вентилятор останавливается до 30 % нагрузки',
    ],
    description:
      'Тот запас, который делает апгрейд видеокарты через два года вопросом пятнадцати минут, а не новой покупки.',
    specs: [
      { key: 'Мощность', value: '850 Вт', primary: true },
      { key: 'Сертификат', value: '80 PLUS Gold', primary: true },
      { key: 'Стандарт', value: 'ATX 3.1 / PCIe 5.1', primary: true },
      { key: 'Модульность', value: 'Полная' },
      { key: 'Разъём 12V-2x6', value: '1 × 600 Вт' },
      { key: 'Вентилятор', value: '120 мм, гидродинамический' },
      { key: 'Уровень шума', value: 'до 22 дБ' },
      { key: 'Глубина', value: '150 мм' },
    ],
    warrantyMonths: 120,
    releasedAt: '2024-07-02',
    buildSlot: 'psu',
    power: 850,
  }),
  p({
    id: 'psu-2',
    slug: 'deepcool-pn650m-650w',
    name: 'Блок питания DeepCool PN650M 650 Вт 80+ Gold ATX 3.1',
    shortName: 'DeepCool PN650M',
    sku: 'R-PN650M-FC0B-EU',
    brand: 'deepcool',
    category: 'psu',
    price: 7990,
    oldPrice: 9490,
    rating: 4.6,
    reviewCount: 84,
    availability: 'in_stock',
    stock: 24,
    badges: ['sale'],
    highlights: [
      'Полная модульность в бюджетном сегменте',
      '12V-2x6 на 450 Вт для карт среднего класса',
      'Японские конденсаторы в первичной цепи',
    ],
    description: 'Честные 650 Вт для сборок с RTX 5060 Ti / RX 9070. Без сюрпризов под нагрузкой.',
    specs: [
      { key: 'Мощность', value: '650 Вт', primary: true },
      { key: 'Сертификат', value: '80 PLUS Gold', primary: true },
      { key: 'Стандарт', value: 'ATX 3.1 / PCIe 5.1', primary: true },
      { key: 'Модульность', value: 'Полная' },
      { key: 'Разъём 12V-2x6', value: '1 × 450 Вт' },
      { key: 'Вентилятор', value: '120 мм FDB' },
      { key: 'Уровень шума', value: 'до 26 дБ' },
      { key: 'Глубина', value: '140 мм' },
    ],
    warrantyMonths: 60,
    releasedAt: '2024-03-19',
    buildSlot: 'psu',
    power: 650,
  }),

  /* --------------------------------------------------------------- Case -- */
  p({
    id: 'case-1',
    slug: 'lian-li-lancool-217',
    name: 'Корпус Lian Li Lancool 217 Mid-Tower',
    shortName: 'Lancool 217',
    sku: 'G99.LAN217B.10',
    brand: 'lian-li',
    category: 'case',
    price: 11990,
    rating: 4.8,
    reviewCount: 57,
    availability: 'in_stock',
    stock: 9,
    badges: ['hit'],
    highlights: [
      'Два 170-мм вентилятора спереди — редкий формат, много воздуха на низких оборотах',
      'Место под башню до 180 мм',
      'Съёмная верхняя панель — удобно ставить СЖО',
    ],
    description:
      'Продуваемый корпус без компромиссов по шуму. Один из немногих, где стоковые вентиляторы менять не нужно.',
    specs: [
      { key: 'Форм-фактор', value: 'Mid-Tower ATX', primary: true },
      { key: 'Поддержка плат', value: 'E-ATX, ATX, mATX, ITX', primary: true },
      { key: 'Длина видеокарты', value: 'до 392 мм', primary: true },
      { key: 'Высота кулера', value: 'до 180 мм' },
      { key: 'Вентиляторы в комплекте', value: '2 × 170 мм + 1 × 140 мм' },
      { key: 'Радиатор сверху', value: 'до 360 мм' },
      { key: 'Отсеки 3.5"', value: '2' },
      { key: 'Передний порт', value: 'USB-C 10 Гбит/с' },
    ],
    warrantyMonths: 24,
    releasedAt: '2023-11-20',
    buildSlot: 'case',
    formFactor: 'ATX',
  }),
  p({
    id: 'case-2',
    slug: 'be-quiet-pure-base-501',
    name: 'Корпус be quiet! Pure Base 501 Airflow',
    shortName: 'Pure Base 501',
    sku: 'BGW61',
    brand: 'be-quiet',
    category: 'case',
    price: 9490,
    rating: 4.7,
    reviewCount: 34,
    availability: 'in_stock',
    stock: 12,
    badges: [],
    highlights: [
      'Шумоизоляция на боковых панелях',
      'Mesh-фронт при этом не душит поток',
      'Быстросъёмные пылевые фильтры',
    ],
    description: 'Компромисс между тишиной и продувом для тех, кто работает рядом с компьютером.',
    specs: [
      { key: 'Форм-фактор', value: 'Mid-Tower ATX', primary: true },
      { key: 'Поддержка плат', value: 'ATX, mATX, ITX', primary: true },
      { key: 'Длина видеокарты', value: 'до 430 мм', primary: true },
      { key: 'Высота кулера', value: 'до 190 мм' },
      { key: 'Вентиляторы в комплекте', value: '2 × 140 мм' },
      { key: 'Радиатор сверху', value: 'до 360 мм' },
      { key: 'Отсеки 3.5"', value: '2' },
      { key: 'Передний порт', value: 'USB-C 10 Гбит/с' },
    ],
    warrantyMonths: 36,
    releasedAt: '2024-04-09',
    buildSlot: 'case',
    formFactor: 'ATX',
  }),

  /* ------------------------------------------------------------ Cooling -- */
  p({
    id: 'cool-1',
    slug: 'thermalright-peerless-assassin-140',
    name: 'Кулер Thermalright Peerless Assassin 140 Digital',
    shortName: 'Peerless Assassin 140',
    sku: 'PA140-D-BL',
    brand: 'thermalright',
    category: 'cooling',
    price: 5490,
    rating: 4.9,
    reviewCount: 198,
    availability: 'in_stock',
    stock: 35,
    badges: ['hit'],
    highlights: [
      'Держит 250 Вт — уровень СЖО за треть цены',
      'Дисплей температуры на крышке',
      'Смещённые башни не перекрывают первый слот памяти',
    ],
    description:
      'Самая частая рекомендация сервиса. Две башни, шесть теплотрубок и адекватные вентиляторы — на этом вопрос охлаждения закрыт.',
    specs: [
      { key: 'Тип', value: 'Воздушный, две башни', primary: true },
      { key: 'Рассеиваемая мощность', value: 'до 265 Вт', primary: true },
      { key: 'Высота', value: '155 мм', primary: true },
      { key: 'Вентиляторы', value: '2 × 140 мм PWM' },
      { key: 'Обороты', value: '1500 об/мин' },
      { key: 'Уровень шума', value: 'до 25.6 дБ' },
      { key: 'Сокеты', value: 'AM5, AM4, LGA1851, LGA1700' },
      { key: 'Термопаста', value: 'В комплекте' },
    ],
    warrantyMonths: 60,
    releasedAt: '2024-06-25',
    buildSlot: 'cooling',
    power: 6,
  }),
  p({
    id: 'cool-2',
    slug: 'deepcool-ld360-aio',
    name: 'Система жидкостного охлаждения DeepCool LD360 360 мм',
    shortName: 'DeepCool LD360',
    sku: 'R-LD360-BKAMNF-G-1',
    brand: 'deepcool',
    category: 'cooling',
    price: 13990,
    oldPrice: 15990,
    rating: 4.6,
    reviewCount: 45,
    availability: 'low_stock',
    stock: 3,
    badges: ['sale'],
    highlights: [
      'Инфинити-зеркало на помпе вместо кричащей подсветки',
      'Держит 9800X3D в стресс-тесте без превышения 80 °C',
      'Шланги в нейлоновой оплётке',
    ],
    description: 'СЖО для корпусов, где нет 160 мм под башню, или когда важен внешний вид сборки.',
    specs: [
      { key: 'Тип', value: 'СЖО, необслуживаемая', primary: true },
      { key: 'Радиатор', value: '360 мм', primary: true },
      { key: 'Рассеиваемая мощность', value: 'до 300 Вт', primary: true },
      { key: 'Вентиляторы', value: '3 × 120 мм PWM' },
      { key: 'Обороты', value: '2250 об/мин' },
      { key: 'Уровень шума', value: 'до 32 дБ' },
      { key: 'Сокеты', value: 'AM5, AM4, LGA1851, LGA1700' },
      { key: 'Длина шлангов', value: '410 мм' },
    ],
    warrantyMonths: 36,
    releasedAt: '2024-08-14',
    buildSlot: 'cooling',
    power: 15,
  }),

  /* ------------------------------------------------------------ Monitor -- */
  p({
    id: 'mon-1',
    slug: 'lg-ultragear-27gx790a-oled',
    name: 'Монитор LG UltraGear 27GX790A-B 27" OLED 480 Гц',
    shortName: 'UltraGear 27GX790A',
    sku: '27GX790A-B',
    brand: 'lg',
    category: 'monitor',
    price: 89990,
    oldPrice: 99990,
    rating: 4.9,
    reviewCount: 27,
    availability: 'low_stock',
    stock: 2,
    badges: ['new', 'sale'],
    highlights: [
      '480 Гц и 0.03 мс — предел того, что различает глаз',
      'Идеальный чёрный: контраст OLED без засветов',
      'Трёхлетняя гарантия с покрытием выгорания',
    ],
    description:
      'Для соревновательных шутеров. После него на обычный IPS смотреть уже не хочется — и это честное предупреждение, а не рекламная фраза.',
    specs: [
      { key: 'Диагональ', value: '27"', primary: true },
      { key: 'Разрешение', value: '2560 × 1440', primary: true },
      { key: 'Матрица', value: 'WOLED', primary: true },
      { key: 'Частота обновления', value: '480 Гц' },
      { key: 'Время отклика', value: '0.03 мс GtG' },
      { key: 'Яркость', value: '1300 кд/м² (пик)' },
      { key: 'Покрытие DCI-P3', value: '98.5 %' },
      { key: 'Разъёмы', value: '2 × HDMI 2.1, DP 2.1, USB-C 90 Вт' },
    ],
    warrantyMonths: 36,
    releasedAt: '2025-03-25',
  }),
  p({
    id: 'mon-2',
    slug: 'samsung-odyssey-g5-32',
    name: 'Монитор Samsung Odyssey G5 32" 2K 180 Гц',
    shortName: 'Odyssey G5 32"',
    sku: 'LS32DG502ENXZW',
    brand: 'samsung',
    category: 'monitor',
    price: 27990,
    rating: 4.6,
    reviewCount: 103,
    availability: 'in_stock',
    stock: 15,
    badges: ['hit'],
    highlights: [
      '32" в 2K — комфортная плотность пикселей для работы и игр',
      '180 Гц без переплаты за OLED',
      'Регулировка по высоте и повороту',
    ],
    description: 'Самая ходовая диагональ. Хватает и для таблиц, и для вечерних сессий.',
    specs: [
      { key: 'Диагональ', value: '32"', primary: true },
      { key: 'Разрешение', value: '2560 × 1440', primary: true },
      { key: 'Матрица', value: 'VA', primary: true },
      { key: 'Частота обновления', value: '180 Гц' },
      { key: 'Время отклика', value: '1 мс MPRT' },
      { key: 'Яркость', value: '350 кд/м²' },
      { key: 'Покрытие sRGB', value: '99 %' },
      { key: 'Разъёмы', value: '2 × HDMI 2.0, DP 1.2' },
    ],
    warrantyMonths: 36,
    releasedAt: '2024-05-30',
  }),

  /* -------------------------------------------------------- Peripherals -- */
  p({
    id: 'per-1',
    slug: 'logitech-g-pro-x-superlight-2',
    name: 'Мышь Logitech G PRO X SUPERLIGHT 2 DEX',
    shortName: 'G PRO X SUPERLIGHT 2',
    sku: '910-007095',
    brand: 'logitech',
    category: 'peripherals',
    price: 14990,
    rating: 4.8,
    reviewCount: 176,
    availability: 'in_stock',
    stock: 21,
    badges: ['hit'],
    highlights: [
      '60 г и 95 часов автономности',
      'Сенсор HERO 2 — 44 000 DPI без сглаживания',
      'Форма DEX под хват «когтем» и «пальцами»',
    ],
    description: 'Стандарт в киберспорте. Лёгкая, предсказуемая, с честным беспроводом на 8000 Гц.',
    specs: [
      { key: 'Тип', value: 'Беспроводная', primary: true },
      { key: 'Вес', value: '60 г', primary: true },
      { key: 'Сенсор', value: 'HERO 2, 44 000 DPI', primary: true },
      { key: 'Частота опроса', value: 'до 8000 Гц' },
      { key: 'Переключатели', value: 'Гибридные оптомеханические' },
      { key: 'Автономность', value: 'до 95 ч' },
      { key: 'Подключение', value: 'LIGHTSPEED, USB-C' },
    ],
    warrantyMonths: 24,
    releasedAt: '2025-01-14',
  }),
  p({
    id: 'per-2',
    slug: 'hyperx-alloy-rise-75',
    name: 'Клавиатура HyperX Alloy Rise 75 механическая',
    shortName: 'Alloy Rise 75',
    sku: '7G7A2AA',
    brand: 'hyperx',
    category: 'peripherals',
    price: 16490,
    oldPrice: 18990,
    rating: 4.7,
    reviewCount: 61,
    availability: 'in_stock',
    stock: 14,
    badges: ['sale'],
    highlights: [
      'Формат 75 % — стрелки на месте, стол свободен',
      'Пять слоёв демпфера: звук «глухой», без гулкости',
      'Hot-swap: переключатели меняются без пайки',
    ],
    description:
      'Клавиатура, которую приятно слушать. Алюминиевая верхняя панель и заводская смазка стабилизаторов — обычно это удел кастомов вдвое дороже.',
    specs: [
      { key: 'Формат', value: '75 %', primary: true },
      { key: 'Переключатели', value: 'HyperX Linear, hot-swap', primary: true },
      { key: 'Подключение', value: 'USB-C, проводное', primary: true },
      { key: 'Частота опроса', value: '8000 Гц' },
      { key: 'Колпачки', value: 'PBT double-shot' },
      { key: 'Корпус', value: 'Алюминий + пластик' },
      { key: 'Подсветка', value: 'RGB на каждую клавишу' },
      { key: 'Вес', value: '1120 г' },
    ],
    warrantyMonths: 24,
    releasedAt: '2024-09-05',
  }),
  p({
    id: 'per-3',
    slug: 'razer-blackshark-v2-pro',
    name: 'Гарнитура Razer BlackShark V2 Pro беспроводная',
    shortName: 'BlackShark V2 Pro',
    sku: 'RZ04-04530100-R3M1',
    brand: 'razer',
    category: 'peripherals',
    price: 21990,
    rating: 4.6,
    reviewCount: 52,
    availability: 'in_stock',
    stock: 8,
    badges: [],
    highlights: [
      'Слышно шаги — без «эквалайзерной магии»',
      '70 часов работы от одного заряда',
      'Съёмный микрофон с шумоподавлением',
    ],
    description: 'Закрытая гарнитура для долгих сессий: не давит на голову, не греет уши.',
    specs: [
      { key: 'Тип', value: 'Полноразмерная закрытая', primary: true },
      { key: 'Подключение', value: '2.4 ГГц, Bluetooth, 3.5 мм', primary: true },
      { key: 'Драйверы', value: '50 мм TriForce', primary: true },
      { key: 'Автономность', value: 'до 70 ч' },
      { key: 'Микрофон', value: 'Съёмный, HyperClear' },
      { key: 'Вес', value: '320 г' },
    ],
    warrantyMonths: 24,
    releasedAt: '2023-08-17',
  }),

  /* ------------------------------------------------------------- Laptop -- */
  p({
    id: 'lap-1',
    slug: 'asus-rog-zephyrus-g14-2025',
    name: 'Ноутбук ASUS ROG Zephyrus G14 (2025) Ryzen 9 / RTX 5070 / 32 ГБ',
    shortName: 'ROG Zephyrus G14',
    sku: 'GA403WR-QS056',
    brand: 'asus',
    category: 'laptop',
    price: 249990,
    oldPrice: 274990,
    rating: 4.8,
    reviewCount: 19,
    availability: 'low_stock',
    stock: 2,
    badges: ['sale', 'exclusive'],
    highlights: [
      'OLED 3K 120 Гц в корпусе толщиной 16 мм',
      '1.5 кг — реально носить каждый день',
      'Заводская калибровка: Delta E < 1',
    ],
    description:
      'Редкое сочетание: производительность игрового ноутбука в корпусе ультрабука. Берут дизайнеры и монтажёры, которым нужна мобильность без потери мощности.',
    specs: [
      { key: 'Процессор', value: 'Ryzen 9 AI HX 370', primary: true },
      { key: 'Видеокарта', value: 'RTX 5070 Laptop 8 ГБ', primary: true },
      { key: 'Экран', value: '14" OLED 2880×1800 120 Гц', primary: true },
      { key: 'Память', value: '32 ГБ LPDDR5X' },
      { key: 'Накопитель', value: '1 ТБ PCIe 4.0' },
      { key: 'Вес', value: '1.5 кг' },
      { key: 'Батарея', value: '73 Вт·ч' },
      { key: 'Порты', value: '2 × USB4, 2 × USB-A, HDMI 2.1, SD' },
    ],
    warrantyMonths: 24,
    releasedAt: '2025-02-04',
  }),
  p({
    id: 'lap-2',
    slug: 'lenovo-ideapad-slim-5-16',
    name: 'Ноутбук Lenovo IdeaPad Slim 5 16" Ryzen 7 / 16 ГБ / 512 ГБ',
    shortName: 'IdeaPad Slim 5 16"',
    sku: '83DC0043RK',
    brand: 'lenovo',
    category: 'laptop',
    price: 74990,
    rating: 4.5,
    reviewCount: 66,
    availability: 'in_stock',
    stock: 11,
    badges: [],
    highlights: [
      '16" 2K для работы с документами и таблицами',
      'До 12 часов автономности',
      'Клавиатура с подсветкой и полноразмерным блоком цифр',
    ],
    description: 'Рабочий ноутбук без игровых понтов. Тихий, лёгкий, с большим экраном.',
    specs: [
      { key: 'Процессор', value: 'Ryzen 7 8845HS', primary: true },
      { key: 'Видеокарта', value: 'Radeon 780M', primary: true },
      { key: 'Экран', value: '16" IPS 2560×1600 120 Гц', primary: true },
      { key: 'Память', value: '16 ГБ LPDDR5X' },
      { key: 'Накопитель', value: '512 ГБ PCIe 4.0' },
      { key: 'Вес', value: '1.89 кг' },
      { key: 'Батарея', value: '75 Вт·ч' },
      { key: 'Порты', value: 'USB-C 3.2, 2 × USB-A, HDMI 2.1' },
    ],
    warrantyMonths: 24,
    releasedAt: '2024-06-11',
  }),

  /* ----------------------------------------------------------- Prebuilt -- */
  p({
    id: 'pre-1',
    slug: 'tochkacomp-derbent-rtx5060ti',
    name: 'Игровой компьютер TochkaComp «Дербент» — Ryzen 5 9600X / RTX 5060 Ti 16 ГБ',
    shortName: 'Сборка «Дербент»',
    sku: 'TC-DRB-2601',
    brand: 'tochkacomp',
    category: 'prebuilt',
    price: 154900,
    oldPrice: 168400,
    rating: 4.9,
    reviewCount: 41,
    availability: 'in_stock',
    stock: 4,
    badges: ['hit', 'sale'],
    highlights: [
      '1440p на высоких в любой актуальной игре',
      'Собрана и протестирована 4 часа под нагрузкой',
      'Гарантия на систему целиком — 3 года',
    ],
    description:
      'Наша самая продаваемая конфигурация. Собрана из комплектующих, которые мы сами ставим себе: холодный процессор, карта с запасом памяти, блок питания с резервом под будущий апгрейд.',
    specs: [
      { key: 'Процессор', value: 'AMD Ryzen 5 9600X', primary: true },
      { key: 'Видеокарта', value: 'RTX 5060 Ti 16 ГБ', primary: true },
      { key: 'Память', value: '32 ГБ DDR5-6000', primary: true },
      { key: 'Накопитель', value: '1 ТБ NVMe Gen4' },
      { key: 'Материнская плата', value: 'B650 ATX' },
      { key: 'Блок питания', value: '650 Вт Gold ATX 3.1' },
      { key: 'Охлаждение', value: 'Башня 2 × 140 мм' },
      { key: 'Корпус', value: 'Mid-Tower mesh' },
    ],
    warrantyMonths: 36,
    releasedAt: '2025-05-12',
  }),
  p({
    id: 'pre-2',
    slug: 'tochkacomp-shamil-rtx5080',
    name: 'Игровой компьютер TochkaComp «Шамиль» — Ryzen 7 9800X3D / RTX 5080',
    shortName: 'Сборка «Шамиль»',
    sku: 'TC-SHM-2602',
    brand: 'tochkacomp',
    category: 'prebuilt',
    price: 389900,
    rating: 5,
    reviewCount: 12,
    availability: 'preorder',
    stock: 0,
    badges: ['preorder', 'exclusive'],
    highlights: [
      '4K/120 без компромиссов',
      'СЖО 360 мм и корпус с полным продувом',
      'Индивидуальный кабель-менеджмент и настройка кривых оборотов',
    ],
    description:
      'Верхняя граница того, что имеет смысл собирать сегодня. Каждый экземпляр настраивается вручную: кривые вентиляторов, лимиты питания, профиль памяти.',
    specs: [
      { key: 'Процессор', value: 'AMD Ryzen 7 9800X3D', primary: true },
      { key: 'Видеокарта', value: 'RTX 5080 16 ГБ', primary: true },
      { key: 'Память', value: '64 ГБ DDR5-6000 CL30', primary: true },
      { key: 'Накопитель', value: '2 ТБ NVMe Gen4 + 2 ТБ Gen4' },
      { key: 'Материнская плата', value: 'X870 ATX' },
      { key: 'Блок питания', value: '1000 Вт Gold ATX 3.1' },
      { key: 'Охлаждение', value: 'СЖО 360 мм' },
      { key: 'Корпус', value: 'Mid-Tower, закалённое стекло' },
    ],
    warrantyMonths: 36,
    releasedAt: '2025-06-01',
  }),
  p({
    id: 'pre-3',
    slug: 'tochkacomp-ofis-tihiy',
    name: 'Компьютер TochkaComp «Офис Тихий» — Ryzen 5 / 16 ГБ / 512 ГБ',
    shortName: 'Сборка «Офис Тихий»',
    sku: 'TC-OFS-2603',
    brand: 'tochkacomp',
    category: 'prebuilt',
    price: 46900,
    rating: 4.7,
    reviewCount: 58,
    availability: 'in_stock',
    stock: 16,
    badges: [],
    highlights: [
      'Почти беззвучный: 21 дБ в простое',
      'Загружается за 8 секунд',
      'Готов к работе из коробки — ОС и офис установлены',
    ],
    description:
      'Для бухгалтерии, ресепшена и учёбы. Без видеокарты, без шума, без лишних трат — но с нормальным SSD и памятью, чтобы не тормозил через год.',
    specs: [
      { key: 'Процессор', value: 'AMD Ryzen 5 8600G', primary: true },
      { key: 'Видеокарта', value: 'Встроенная Radeon 760M', primary: true },
      { key: 'Память', value: '16 ГБ DDR5-5600', primary: true },
      { key: 'Накопитель', value: '512 ГБ NVMe Gen4' },
      { key: 'Материнская плата', value: 'B650 micro-ATX' },
      { key: 'Блок питания', value: '450 Вт Bronze' },
      { key: 'Охлаждение', value: 'Башня 120 мм' },
      { key: 'Корпус', value: 'Micro-Tower' },
    ],
    warrantyMonths: 36,
    releasedAt: '2025-04-02',
  }),
];

export const reviews: Review[] = [
  {
    id: 'r1',
    productSlug: 'tochkacomp-derbent-rtx5060ti',
    author: 'Марат А.',
    city: 'Махачкала',
    rating: 5,
    createdAt: '2026-05-18',
    title: 'Забрал в тот же день',
    body: 'Заказал утром, к вечеру уже играл. Показали стресс-тест прямо в магазине, температуры и правда как обещали. Кабели уложены аккуратно — видно, что собирали руками, а не на конвейере.',
    verified: true,
  },
  {
    id: 'r2',
    productSlug: 'palit-rtx-5070-ti-gamingpro-16gb',
    author: 'Заур М.',
    city: 'Каспийск',
    rating: 5,
    createdAt: '2026-04-27',
    title: 'Тихая даже под нагрузкой',
    body: 'Брал на замену 3070. В закрытом корпусе слышно только когда специально прислушиваешься. В 4K с DLSS всё летает.',
    verified: true,
  },
  {
    id: 'r3',
    productSlug: 'amd-ryzen-7-9800x3d',
    author: 'Ислам Г.',
    city: 'Махачкала',
    rating: 5,
    createdAt: '2026-06-02',
    title: 'В симуляторах разница огромная',
    body: 'Пересел с 5600X. В стратегиях поздние ходы стали в два раза быстрее. Кулер сразу берите нормальный, на стоке греется.',
    verified: true,
  },
  {
    id: 'r4',
    productSlug: 'thermalright-peerless-assassin-140',
    author: 'Тимур Р.',
    city: 'Дербент',
    rating: 5,
    createdAt: '2026-03-11',
    title: 'За свои деньги — лучшее',
    body: 'Поставил на 9800X3D, в стресс-тесте максимум 78 градусов. Помогли подобрать по высоте корпуса, сам бы не угадал.',
    verified: true,
  },
  {
    id: 'r5',
    productSlug: 'samsung-990-pro-2tb',
    author: 'Патимат К.',
    city: 'Махачкала',
    rating: 5,
    createdAt: '2026-05-30',
    title: 'Перенесли данные бесплатно',
    body: 'Пришла со старым ноутбуком, попросили просто продать диск. В итоге перенесли всю систему со старого на новый и ничего не взяли за это. Работает ощутимо быстрее.',
    verified: true,
  },
  {
    id: 'r6',
    productSlug: 'lg-ultragear-27gx790a-oled',
    author: 'Рустам Х.',
    city: 'Махачкала',
    rating: 4,
    createdAt: '2026-06-14',
    title: 'Картинка отличная, но нужен свет',
    body: 'OLED есть OLED — чёрный настоящий. В солнечный день на бликах видно отражения, стол пришлось развернуть. Ко всему остальному претензий нет.',
    verified: true,
  },
  {
    id: 'r7',
    productSlug: 'hyperx-alloy-rise-75',
    author: 'Амина С.',
    city: 'Избербаш',
    rating: 5,
    createdAt: '2026-02-08',
    title: 'Звук приятный, соседи не жалуются',
    body: 'Долго выбирала между несколькими, дали пощёлкать на витрине все. Взяла эту — печатать реально приятнее, чем на мембранной.',
    verified: true,
  },
  {
    id: 'r8',
    productSlug: 'be-quiet-pure-power-13-m-850w',
    author: 'Гаджи О.',
    city: 'Хасавюрт',
    rating: 5,
    createdAt: '2026-01-22',
    title: 'Взял с запасом — не пожалел',
    body: 'Отговорили от 650 Вт, объяснили про пики новых карт. Через полгода поменял видеокарту на более мощную — блок трогать не пришлось.',
    verified: true,
  },
];
